In [1]:
import pandas as pd

In [4]:
pd.read_csv('C:\\Users\\Administrador_BI\\Desktop\\VOLCADO_22.csv')

C:\Users\Administrador_BI\AppData\Local\Temp\ipykernel_14900\1022315571.py:1: DtypeWarning: Columns (3,21,23,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('C:\\Users\\Administrador_BI\\Desktop\\VOLCADO_22.csv')

,Campaña,Empresa,Nombre,DNI,Telefono,Concepto,Concepto_1,Concepto_2,Concepto_3,Concepto_4,...,Nombre_Agente,Departamento,Provincia,Distrito,velocidad regular,precio regular,velocidad promocion,precio promocion,tipo hogar,promocion oferta
0,OUTSJL,GEATEL,ALIPIO,9156191.0,947586476.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,ANGEL FERREYROS RAMIREZ,NaN,SAN BORJA,LIMA - LIMA,500 MNPS,129.9,1000 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES
1,OUTSJL,GEATEL,BRUNO SILVESTRE YARANGA GUTIER,42061710.0,951325519.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,RUTH ESTHER QUISPE QUISPE,Ca,CALLAO,CALLAO,450 MBPS,89.9,700 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES
2,WINOUT,IGLOBAL,CARLOS NOE GORDON CANAYO,47698825.0,978531540.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,MARIA JOSE DE LOS MILAGROS MORAN VIDALON,NaN,Chorrillos,Lima-Lima,450 MBPS,89.0,700 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES
3,WINOUT,IGLOBAL,CESAR ALBERTO BEJARANO LAZO,43402942.0,943455554.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,DAVID ASENCIOS LOA,NaN,Santiago de Surco,Lima,450 MBPS,89.9,700 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES
4,WINOUT,IGLOBAL,CESAR AUGUSTO CORDOVA DURAND,46439605.0,921020970.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,JASSMIN DELIA PANDURO ZAPANA,NaN,Los Olivos,Lima,450 MBPS,89.9,700 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168810,WINOUT,IGLOBAL,JORGE IGNACIO PUGA GARCIA,74500239,939597827.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,CRISTIAN YOVANNY QUISPE HUAYTALLA (BACKOFFICE),LIMA,LIMA,LOS OLIVOS,450 MBPS,89.0,700 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES
168811,WINOUT,IGLOBAL,ILDEFONSO CARTOLIN PESEROS,9252992,918593530.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,ALEXIS ARTURO SILVA RUIZ,LIMA,LIMA,SAN JUAN MIRAFLORES,450 MBPS,89.0,700 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES
168812,WINOUT,IGLOBAL,EDWIN RIVERA ALMAYDA,45689481,929313803.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,YSABELINA LOA RAMOS,LIMA,LIMA,LA VICTORIA,450 MBPS,89.9,700 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES
168813,WINOUT,IGLOBAL,LUIS ENRIQUE MORALES TAYPE,80276054,960251088.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,CRISTHIAN QUIJANO HUANCA OJT,LIMA,LIMA,SAN JUAN DE LURIGANCHO,450 MBPS,89.9,700 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES
168814,WINOUT,IGLOBAL,ANA CECILIA PEÑA LLAMO,48867808,930953523.0,Contacto Efectivo,Si Autoriza,Venta,Venta,Venta,...,YSABELINA LOA RAMOS,LAMBAYEQUE,CHICLAYO,JOSE LEONARDO ORTIZ,550 MBPS,89.0,700 MBPS,1.0,HORIZONTAL,S/1 POR 2 MESES

In [ ]:
pd.read_excel('C:\\Users\\Administrador_BI\\Desktop\\ABRAHAM\\GESTION WIN - SJM.xlsx')

,LIST_ID,CAMPAÑA,FECHA,TMO,STATUS,TIPIFICACION,TELEFONO,DNI,AGENTE,TERMINO_LLAMADA,TIPO_LLAMADA,GESTION,AGENDADO,VENTA,VOLVER A LLAMAR,CORTA LLAMADA,TIPOLOGÌA
0,408,WINOUT,2025-10-01,00:20:38,2CNE03,AUTORIZA- SIN COBERTURA,968050812,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Correcta
1,404,WINOUT,2025-10-01,00:12:44,1CEF02,AUTORIZA - AGENDADO,950168047,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Sospechosa
2,404,WINOUT,2025-10-01,00:08:35,2CNE03,AUTORIZA- SIN COBERTURA,945853311,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Correcta
3,408,WINOUT,2025-10-01,00:04:53,2CNE01,AUTORIZA- CORTA LLAMADA,972819271,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Sospechosa
4,404,WINOUT,2025-10-01,00:03:57,2CNE01,AUTORIZA- CORTA LLAMADA,955258851,46691128,HAUDE DAVID CALDERON SAN MIGUEL,AGENTE,AUTO,OPERACIONES,0,0,0,0,Sospechosa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,404,WINOUT,2025-10-01,00:00:10,2CNE01,AUTORIZA- CORTA LLAMADA,975245885,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,1,1,1,1,Sospechosa
158,407,WINOUT,2025-10-01,00:00:08,2CNE01,AUTORIZA- CORTA LLAMADA,939410238,46691128,HAUDE DAVID CALDERON SAN MIGUEL,AGENTE,AUTO,OPERACIONES,1,1,1,1,Sospechosa
159,407,WINOUT,2025-10-01,00:00:05,2CNE01,AUTORIZA- CORTA LLAMADA,948346203,46691128,HAUDE DAVID CALDERON SAN MIGUEL,AGENTE,MANUAL,OPERACIONES,1,1,1,1,Sospechosa
160,407,WINOUT,2025-10-01,00:00:51,1CEF10,AUTORIZA - VOLVER A LLAMAR,903399329,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Correcta
161,404,WINOUT,2025-10-01,00:00:03,1CEF10,AUTORIZA - VOLVER A LLAMAR,989316547,46691128,HAUDE DAVID CALDERON SAN MIGUEL,AGENTE,AUTO,OPERACIONES,1,1,1,1,Correcta

In [ ]:
# nrows
pd.read_excel('C:\\Users\\Administrador_BI\\Desktop\\ABRAHAM\\GESTION WIN - SJM.xlsx', nrows=5)

,LIST_ID,CAMPAÑA,FECHA,TMO,STATUS,TIPIFICACION,TELEFONO,DNI,AGENTE,TERMINO_LLAMADA,TIPO_LLAMADA,GESTION,AGENDADO,VENTA,VOLVER A LLAMAR,CORTA LLAMADA,TIPOLOGÌA
0,408,WINOUT,2025-10-01,00:20:38,2CNE03,AUTORIZA- SIN COBERTURA,968050812,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Correcta
1,404,WINOUT,2025-10-01,00:12:44,1CEF02,AUTORIZA - AGENDADO,950168047,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Sospechosa
2,404,WINOUT,2025-10-01,00:08:35,2CNE03,AUTORIZA- SIN COBERTURA,945853311,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Correcta
3,408,WINOUT,2025-10-01,00:04:53,2CNE01,AUTORIZA- CORTA LLAMADA,972819271,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Sospechosa
4,404,WINOUT,2025-10-01,00:03:57,2CNE01,AUTORIZA- CORTA LLAMADA,955258851,46691128,HAUDE DAVID CALDERON SAN MIGUEL,AGENTE,AUTO,OPERACIONES,0,0,0,0,Sospechosa

## usecols

In [ ]:
# usecols
pd.read_excel('C:\\Users\\Administrador_BI\\Desktop\\ABRAHAM\\GESTION WIN - SJM.xlsx', usecols=['LIST_ID','CAMPAÑA','AGENTE'])

     LIST_ID CAMPAÑA                           AGENTE
0        408  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL
1        404  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL
2        404  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL
3        408  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL
4        404  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL
..       ...     ...                              ...
157      404  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL
158      407  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL
159      407  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL
160      407  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL
161      404  WINOUT  HAUDE DAVID CALDERON SAN MIGUEL

[162 rows x 3 columns]

In [ ]:
combo = pd.read_excel('C:\\Users\\Administrador_BI\\Desktop\\ABRAHAM\\GESTION WIN - SJM.xlsx', sheet_name=4)
combo

,504,WINOUT,2025-10-01 00:00:00,00:00:00,3NCO03,CASILLA DE VOZ,988000723,46691128,HAUDE DAVID CALDERON SAN MIGUEL,AGENTE,MANUAL,OPERACIONES,NaN,1,1.1,1.2,Correcta
0,404,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,968230838,73285107,JEAN PAUL SALAMANCA TORRES,AGENTE,MANUAL,OPERACIONES,1,1,1,1,Sospechosa
1,404,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,968230838,73285107,JEAN PAUL SALAMANCA TORRES,AGENTE,MANUAL,OPERACIONES,1,1,1,1,Sospechosa
2,404,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,960370449,73003562,DARIO DARWIN MAMANI JARA,AGENTE,MANUAL,OPERACIONES,1,1,1,1,Sospechosa
3,404,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,941891116,74973677,JEYSON PAUL ESPINOZA DIAZ,AGENTE,MANUAL,OPERACIONES,1,1,1,1,Sospechosa
4,998,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,983605813,10015709,YSABELINA LOA RAMOS,AGENTE,MANUAL,OPERACIONES,1,1,1,1,Sospechosa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7740,404,WINOUT,2025-10-01,00:07:05,1CEF02,AUTORIZA - AGENDADO,939459185,76845893,MARYOLEI LILIBETH MORALES LOPEZ,AGENTE,AUTO,OPERACIONES,1,0,0,0,Sospechosa
7741,404,WINOUT,2025-10-01,00:07:13,1CEF09,AUTORIZA- CONF CON SU OPERADOR,929377400,70494580,NICOLE GERALDINE YGUIA ARANCIBIA,CLIENTE,AUTO,OPERACIONES,1,0,0,0,Sospechosa
7742,407,WINOUT,2025-10-01,00:07:22,1CEF02,AUTORIZA - AGENDADO,947367531,75200837,AGUILAR MOLINA JOSEPH MICHAEL,AGENTE,AUTO,OPERACIONES,1,0,0,0,Sospechosa
7743,408,WINOUT,2025-10-01,00:07:24,2CNE07,NO AUTORIZA COMUNICACION,920897929,60768353,JOSEPH ISMAEL LA ROSA SHISCHES,CLIENTE,AUTO,OPERACIONES,1,0,0,0,Sospechosa
7744,408,WINOUT,2025-10-01,00:07:26,2CNE03,AUTORIZA- SIN COBERTURA,969081754,10015709,YSABELINA LOA RAMOS,CLIENTE,AUTO,OPERACIONES,1,0,0,0,Correcta

In [ ]:
# Para guardaer un excel modificado con pyton
import pandas as pd

bodo = pd.read_excel('C:\\Users\\Administrador_BI\\Desktop\\GESTION WIN - SJM.xlsx', header=None, 
    names=[
        'LIST_ID','CAMPAÑA','FECHA','TMO','STATUS','TIPIFICACION',
        'TELEFONO','DNI','AGENTE','TERMINO_LLAMADA','TIPO_LLAMADA',
        'GESTION','AGENDADO','VENTA','VOLVER A LLAMAR',
        'CORTA LLAMADA','TIPOLOGÌA'
    ], sheet_name='combo'
)
bodo.to_excel(r'C:\Users\Administrador_BI\Desktop\nuevo.xlsx', index=False)